BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-nexigon-rauc"
BBFILE_PATTERN_meta-nexigon-rauc = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-nexigon-rauc = "8"

LAYERDEPENDS_meta-nexigon-rauc = "core meta-nexigon-core"
LAYERSERIES_COMPAT_meta-nexigon-rauc = "scarthgap"
