BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-nexigon-rugix"
BBFILE_PATTERN_meta-nexigon-rugix = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-nexigon-rugix = "6"

LAYERDEPENDS_meta-nexigon-rugix = "core meta-nexigon-core"
LAYERSERIES_COMPAT_meta-nexigon-rugix = "scarthgap"
